// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: api/proto/producer.proto

package messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProducerPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Topic   string `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ProducerPayload) Reset() {
	*x = ProducerPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_producer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerPayload) ProtoMessage() {}

func (x *ProducerPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_producer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerPayload.ProtoReflect.Descriptor instead.
func (*ProducerPayload) Descriptor() ([]byte, []int) {
	return file_api_proto_producer_proto_rawDescGZIP(), []int{0}
}

func (x *ProducerPayload) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProducerPayload) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type ProducerAsk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ask bool `protobuf:"varint,1,opt,name=ask,proto3" json:"ask,omitempty"`
}

func (x *ProducerAsk) Reset() {
	*x = ProducerAsk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_producer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerAsk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerAsk) ProtoMessage() {}

func (x *ProducerAsk) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_producer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerAsk.ProtoReflect.Descriptor instead.
func (*ProducerAsk) Descriptor() ([]byte, []int) {
	return file_api_proto_producer_proto_rawDescGZIP(), []int{1}
}

func (x *ProducerAsk) GetAsk() bool {
	if x != nil {
		return x.Ask
	}
	return false
}

var File_api_proto_producer_proto protoreflect.FileDescriptor

var file_api_proto_producer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0f, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f,
	0x70, 0x69, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x1f, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x41, 0x73, 0x6b, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x61, 0x73, 0x6b, 0x42, 0x19,
	0x5a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_proto_producer_proto_rawDescOnce sync.Once
	file_api_proto_producer_proto_rawDescData = file_api_proto_producer_proto_rawDesc
)

func file_api_proto_producer_proto_rawDescGZIP() []byte {
	file_api_proto_producer_proto_rawDescOnce.Do(func() {
		file_api_proto_producer_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_producer_proto_rawDescData)
	})
	return file_api_proto_producer_proto_rawDescData
}

var file_api_proto_producer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_producer_proto_goTypes = []interface{}{
	(*ProducerPayload)(nil), // 0: ProducerPayload
	(*ProducerAsk)(nil),     // 1: ProducerAsk
}
var file_api_proto_producer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_producer_proto_init() }
func file_api_proto_producer_proto_init() {
	if File_api_proto_producer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_producer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_producer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerAsk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_producer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_producer_proto_goTypes,
		DependencyIndexes: file_api_proto_producer_proto_depIdxs,
		MessageInfos:      file_api_proto_producer_proto_msgTypes,
	}.Build()
	File_api_proto_producer_proto = out.File
	file_api_proto_producer_proto_rawDesc = nil
	file_api_proto_producer_proto_goTypes = nil
	file_api_proto_producer_proto_depIdxs = nil
}
